name: Typescript CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependency installation complete."

      - name: Build
        run: |
          echo "Compiling the code..."
          npm run compile
          echo "Compile complete."

      - name: Lint
        run: |
          echo "Running Linter..."
          npm run lint
          echo "Running Linter complete."

      - name: Format check
        run: |
          echo "Running format check..."
          npm run format-check
          echo "Format check complete."

      - name: Test apply patches
        run: |
          set -e
          for patch in *.patch; do
            if [ -f "$patch" ]; then
              echo "Testing $patch"
              git apply --check -v "$patch" || (echo "Failed to apply patch: $patch" && exit 1)
            fi
          done
          echo "No patches to test or all patches applied successfully."

      - name: Check if Jenkins Trigger workflow exists
        id: check-file
        run: |
          if [ -f .github/workflows/jenkins-trigger.yml ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Trigger Jenkins Workflow
        if: env.file_exists == 'true'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-workflow-2"}'
          echo "Jenkins Workflow triggered!"